version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: optiroute-postgres
    environment:
      POSTGRES_DB: optiroute
      POSTGRES_USER: optiroute_user
      POSTGRES_PASSWORD: optiroute_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U optiroute_user -d optiroute"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: optiroute-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@optiroute.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 