spring:
  application:
    name: optiroute
  datasource:
    url: jdbc:postgresql://localhost:5432/optiroute
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret}
  expiration: 86400000

logging:
  level:
    root: INFO
    com.optiroute: DEBUG
    org.springframework.security: INFO 